### ISSUE TITLE
Need Chinese translation, please contact me

### ISSUE THREAD

**Issue by pklloveyou** [AzerothShard/playermap#1]
Need Chinese translation, please contact me, email pkl_ long@163.com

**Comment by pklloveyou** [comment]
@Helias Do you need it?

**Comment by Helias** [comment]
No, but it would be nice to add the multi-lang in this app

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/104968248-4d768b80-5a20-11eb-8eb5-5e0ac6698771.png)

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/104968261-56fff380-5a20-11eb-81f1-631374318a40.png)

**Comment by pklloveyou** [comment]
I have translated these two documents

**Comment by Helias** [comment]
you could make another branch in https://github.com/azerothcore/playermap
or I can create it and you can push a PR there

**Comment by pklloveyou** [comment]
I'll send it to you by email

**Comment by Helias** [comment]
ok, ty

**Comment by pklloveyou** [comment]
I sent it

**Comment by lansh810** [comment]
The configuration file ‘playermap_config.php’ in the config directory does not clearly state the correct syntax for setting the language to Chinese. None of the following attempts worked: ‘zh’, ‘zhcn’, ‘zh-cn’, ‘ch’, ‘chinese’. Please provide the correct syntax for setting the language to Chinese.
